### ISSUE TITLE
Error renaming transcoded video

### ISSUE THREAD

**Issue by imperatormk** [prologic/tube#1]
I'm getting this error when I try to upload a video locally with all default settings:

error renaming transcoded video: rename uploads\tube-transcode-399718650.mp4 videos\qRmbsx7Tv7ciEX4XQ7onJd.mp4: The process cannot access the file because it is being used by another process.

Using go version go1.14.1 windows/amd64

**Comment by prologic** [comment]
I wonder whether this is a timing issue on Windows. AFAIK Windows holds file locks on open files and `ffmpeg` is being used in the background to do the transcoding. Aldo did/do you even have `ffmpeg` on your system? As I don't have a WIndows system myself it will be quite difficult for me to debug this :/ I will need some help!

**Comment by prologic** [comment]
I won't be able to reproduce or fix this as I don't have access to a Windows development machine. If anyone is able to test/repro and fix this from a Windows machine, Please put up a PR! Meanwhile I will close this as "can't fix".

**Comment by pierlucg-xs** [comment]
This definitely sounds like a timing issue where the lock is kept for a short while after ffmpeg is done. Aside from adding a small sleep (🤢), I'm not sure what can be done about it.

**Comment by prologic** [comment]
Happy to have a PR for a small sleep.

In an ideal world however I'd refactor the "work" to be async with some kind of "view" to see when your "transcoding" is ready.
