### ISSUE TITLE
Unable to upload 100MB+ video

### ISSUE THREAD

**Issue by bearx3f** [prologic/tube#19]
I've changed `config.json` to

```
{
   max_upload_size: 2147483647
}
```

but still unable to upload 300MB file 

I found you hard-coded file size in `upload.js`

https://github.com/prologic/tube/blob/cb8d61538dac417f3534558e864e9982616c2010/static/upload.js#L5

**Comment by prologic** [comment]
@bearx3f If you would be willing to put up a PR to fix this I would happily review and accept it!

You basically need to modify the context passed into the templates so that we can pass this value to the client-side Javascript onthe Upload form.
