### ISSUE TITLE
error "generating thumbnail" while uploading the video.

### ISSUE THREAD

**Issue by Apoorva-Paneliya** [prologic/tube#21]
step to reproduce
1. Download linux binary.
2. run application ./tube
3. Try to upload video file.

Observation:-
**error generating thumbnail: cmd.CombinedOutput error: exit status 1 mt: invalid option -- 'b' Try 'mt --help' or 'mt --usage' for more information.**

**Comment by prologic** [comment]
Hello Can you please show me the output of

```sh
$ command -v mt
$ mt --help
```

on your system?

I suspect you have a different `mt` binary on your system than the one being expected to be used by `tube` here :/ However #16 should eventually fix this (@mutschler How are we doing with this? :D)

**Comment by Apoorva-Paneliya** [comment]
Below are the output of above mentioned command

````shell
$ command -v mt
/bin/mt

$ mt --help
Usage: mt [OPTION...] operation [count]
control magnetic tape drive operation

  -f, --file=DEVICE          use device as the file name of the tape drive to
                             operate on
      --rsh-command=COMMAND  use remote COMMAND instead of rsh
  -?, --help                 give this help list
      --usage                give a short usage message
  -V, --version              print program version

Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.

Report bugs to <bug-cpio@gnu.org>.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

`````
Until this issue gets fixed, Is there a way to disable this thumbnail feature and get it to working condition ?

Thank you very much for developing this.

**Comment by prologic** [comment]
Hmmm 🤔what you'reshowingg me is an unfortunate conincidance :/ 

> Until this issue gets fixed, Is there a way to disable this thumbnail feature and get it to working condition ?

Unfortunately not at this time; but I will add this feature this long-weekend.

**Comment by mutschler** [comment]
@prologic yeah there's a linux mt command for handling magnetic tape drives (didn't know about that till i've already released everything) so my fix for this would be to call mt with the complete path (guess that would be here https://github.com/prologic/tube/blob/20bf93c86d7453d4ac1bdaf6bd2679f49d5951e9/app/app.go#L295)

**Comment by prologic** [comment]
> sadly i didn't find any time to start refactoring the code for library usage -.-

That's okay ) We'll find a way forward I'm sure!

**Comment by prologic** [comment]
This still needs to get done. I have very little bandwidth at the moment due to my day job but I welcome anyone from the community to put up PR(s)!

**Comment by adelorenzo** [comment]
I fixed the issue with a workaround.

1. rename the original `mt` utility to for instance `mt-old`
2. download the `mt` thumbnailer tool from here: https://github.com/mutschler/mt according to the machine type (in my case `mt-1.0.10-arm-linux-gnueabihf.tar.gz`)
3. untar and mv `mt-1.0.10-arm-linux-gnueabihf` to /usr/local/bin/ as `mt`
4. restart `tube`

**Comment by prologic** [comment]
Ping @mutschler re #16 🤗

**Comment by mutschler** [comment]
Sadly i still wasn't able to make any progress regarding the library use rewrite due to work piling up, it's still on my list though
