### ISSUE TITLE
Add tags to get embed information

### ISSUE THREAD

**Issue by LelouBil** [prologic/tube#24]
As an Improvement I suggest adding tags like [opengraphs](https://ogp.me/), or support [oembed](https://oembed.com/) to have the video thumbnail and title show up when linking on social media or even the video playable in an embed.

**Comment by prologic** [comment]
I agree. I did this for [jointwt/twtxt](https://github.com/jointwt/twtxt)

Do you want to submit a PR for this?

**Comment by LelouBil** [comment]
I tried messing with it a bit but I couldn't get it to work on discord (where I wanted the embeds in the first place) and I'm not sure of what tags to add since there are multiple standards

**Comment by LelouBil** [comment]
PR added

**Comment by prologic** [comment]
PR merged
