### ISSUE TITLE
Github actions for PR are mentioning files that do not exist and have unclear error messages

### ISSUE THREAD

**Issue by LelouBil** [prologic/tube#26]
I just did a PR and and the `assignAuthor `action errored like so 
```
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```

The `greetings` action also errored like this `Error: Resource not accessible by integration`

These messages are not very descriptive. 

The `greetings` action text also taks about CONTRIBUTING.md and CODE_OF_CONDUCT.md files, however I do not see them in the repo.

**Comment by prologic** [comment]
I will remove these actions. I find them less useful anyway. Thanks for brining this up!
