### ISSUE TITLE
error message from upload improvement

### ISSUE THREAD

**Issue by tatic0** [prologic/tube#30]
Hello,

The file **upload.js** returns an error when the file is too big.
  The error message says "Please select more small file"

It should say "Please select a smaller file"

**Comment by prologic** [comment]
Yes sorry about that. Someone else did the UI for that part and his English wasn't that great 🤣

Please submit a PR to fix this I'll happily merge it!

**Comment by tatic0** [comment]
PR submitted

**Comment by tatic0** [comment]
PR accepted, branch deleted to minimize clutter.
