### ISSUE TITLE
Disable upload from config file

### ISSUE THREAD

**Issue by tatic0** [prologic/tube#31]
Would it be possible to add an option to disable the upload button from the config(.json) file?

**Comment by prologic** [comment]
There is no support for this now.

But a PR to implement this is welcome!

**Comment by Bugz000** [comment]
i would also like this feature, the majority of folk running this are wanting to share their own videos - not become the next "imgur" for videos... but i can't even get it working, install directions need an overhaul, once working i will see about binding UPLOAD to a specific or local addresses only - and perhaps issuing a better worded install guide as from what i gather, english is not the native language of any member of the dev team and it is confusing

**Comment by tatic0** [comment]
Ok, challenge accepted, I'll teach myself to code and then come back with a(nother) PR :)
