### ISSUE TITLE
change max size of video

### ISSUE THREAD

**Issue by yulman19** [prologic/tube#7]
First of all, thank you for this project.

Is there a config file where i can change the max size of the video? why is there a limit

Thanks

**Comment by prologic** [comment]
Yes! The default is in the top-level [config.json](/config.json) -- You can use that asa. base and modify to suit and run with `tube -c /path/to/config`. The relevant section you want is:

```json
"server": {
  "max_upload_size": XXX
}
```

**Comment by prologic** [comment]
@yulman19 I've added a section on configuration in the [README](/README.md) in #10 If you could review this and approve I will merge it and close this issue :) Thanks for reporting!

**Comment by bearx3f** [comment]
I've change

```
{
   max_upload_size: 2147483647
}
```

but still unable to upload 300M file 

I found you hard-coded file size in upload.js

https://github.com/prologic/tube/blob/cb8d61538dac417f3534558e864e9982616c2010/static/upload.js#L5

**Comment by prologic** [comment]
Whoops :) Can you file a bug? That's a bug in the frontend code :)

**Comment by bearx3f** [comment]
> Whoops :) Can you file a bug? That's a bug in the frontend code :)

yes 😁
